name:                quickcheck-combinators
version:             0.0.6
github:              "athanclark/quickcheck-combinators"
license:             BSD3
author:              "Athan Clark"
maintainer:          "athan.clark@gmail.com"
copyright:           "2023 (c) Athan Clark"
category:            Test
synopsis:            "Simple type-level combinators for augmenting QuickCheck instances."

extra-source-files:
- README.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/athanclark/quickcheck-combinators#README>

dependencies:
- base >= 4.11 && < 5
- QuickCheck
- unfoldable-restricted >= 0.0.1
- unit-constraint

ghc-options:
  - -Wall

library:
  source-dirs: src
